// ============================================================
// WASTELAND DRIVERS ACADEMY — Card Database
// A collectible-card-game study deck for the WA State Driver Guide
// ============================================================

// Rarities (with drop rates for pack opening)
const RARITY = {
  common:    { label: "Common",    color: "#9ca3af", glow: "rgba(156,163,175,0.5)",  weight: 50 },
  uncommon:  { label: "Uncommon",  color: "#22d3ee", glow: "rgba(34,211,238,0.55)",  weight: 30 },
  rare:      { label: "Rare",      color: "#ec4899", glow: "rgba(236,72,153,0.65)",  weight: 14 },
  mythic:    { label: "Mythic",    color: "#a855f7", glow: "rgba(168,85,247,0.75)",  weight: 5  },
  forbidden: { label: "Forbidden", color: "#f43f5e", glow: "rgba(244,63,94,0.9)",    weight: 1  }
};

// Suits / Schools (color affiliations a la MTG)
const SUIT = {
  blood:     { label: "Blood",     symbol: "🜂", color: "#dc2626", desc: "DUI · BAC · alcohol" },
  ember:     { label: "Ember",     symbol: "✿", color: "#84cc16", desc: "Cannabis · THC" },
  static:    { label: "Static",    symbol: "⚡", color: "#f472b6", desc: "Distraction · phones" },
  iron:      { label: "Iron",      symbol: "✶", color: "#94a3b8", desc: "Road signs" },
  thorn:     { label: "Thorn",     symbol: "❦", color: "#a855f7", desc: "Right of way" },
  bone:      { label: "Bone",      symbol: "☽", color: "#e0e7ef", desc: "Speed · numbers" }
};

// Cards. Each card has a study side (the actual exam content)
// and a flavor side (TCG-style stats and lore for fun).
const CARDS = [
  // ===== BLOOD (BAC / ALCOHOL) =====
  {
    id: "blood-001",
    name: "Crimson Catalyst",
    subtitle: "The 0.08 Threshold",
    suit: "blood",
    rarity: "mythic",
    cost: 8,
    atk: 8, def: 8,
    art: "images/bac.png",
    type: "Adult DUI",
    rules: "Adult drivers 21+: a Blood Alcohol Concentration of 0.08% or higher within 2 hours of driving = per se DUI under RCW 46.61.502. No additional proof of impairment needed.",
    flavor: "Eight drops in a hundred. Eight reasons to lose everything.",
    keyNumber: "0.08%",
    category: "BAC & Alcohol",
    difficulty: "Easy",
    frequency: 5
  },
  {
    id: "blood-002",
    name: "Cradle of Zero",
    subtitle: "Minor's Curse",
    suit: "blood",
    rarity: "rare",
    cost: 5,
    atk: 5, def: 7,
    art: null,
    icon: "🩸",
    type: "Zero Tolerance",
    rules: "Drivers under 21: ANY BAC of 0.02% or higher within 2 hours of driving = Minor DUI misdemeanor (RCW 46.61.503). Up to 90 days jail + $1,000 fine + 90-day suspension.",
    flavor: "Youth is no shield. Two drops will break it.",
    keyNumber: "0.02%",
    category: "BAC & Alcohol",
    difficulty: "Easy",
    frequency: 5
  },
  {
    id: "blood-003",
    name: "Iron Yoke of the Trucker",
    subtitle: "Commercial Restriction",
    suit: "blood",
    rarity: "uncommon",
    cost: 4,
    atk: 4, def: 6,
    art: null,
    icon: "🛻",
    type: "CDL Limit",
    rules: "Drivers operating a commercial vehicle: BAC limit is 0.04% — exactly half the standard adult limit. Stricter responsibility, stricter law.",
    flavor: "When you drive the beast, the leash tightens.",
    keyNumber: "0.04%",
    category: "BAC & Alcohol",
    difficulty: "Medium",
    frequency: 3
  },
  {
    id: "blood-004",
    name: "The Aggravated Verdict",
    subtitle: "Beyond the Veil",
    suit: "blood",
    rarity: "rare",
    cost: 7,
    atk: 9, def: 4,
    art: null,
    icon: "⚖️",
    type: "Enhanced Penalty",
    rules: "BAC of 0.15% or higher triggers aggravated DUI: longer license suspension, mandatory ignition interlock, larger fines, and longer jail terms.",
    flavor: "Some thresholds, once crossed, cannot be uncrossed.",
    keyNumber: "0.15%",
    category: "BAC & Alcohol",
    difficulty: "Hard",
    frequency: 2
  },
  {
    id: "blood-005",
    name: "Shatter the Lie",
    subtitle: "The Refusal",
    suit: "blood",
    rarity: "mythic",
    cost: 6,
    atk: 7, def: 7,
    art: "images/refusal.png",
    type: "Implied Consent",
    rules: "Refusing a chemical (breath/blood) test in WA = automatic license suspension of 90 to 730 days (or until age 21, whichever is longer). Refusal can be used against you in court.",
    flavor: "Silence is not safety. The chains find you anyway.",
    keyNumber: "90–730 days",
    category: "BAC & Alcohol",
    difficulty: "Medium",
    frequency: 3
  },
  {
    id: "blood-006",
    name: "Hourglass of Veins",
    subtitle: "The 2-Hour Rule",
    suit: "blood",
    rarity: "uncommon",
    cost: 3,
    atk: 3, def: 5,
    art: null,
    icon: "⏳",
    type: "Test Window",
    rules: "Washington's per se BAC and THC limits apply to concentrations measured within 2 HOURS after operating or being in physical control of a vehicle.",
    flavor: "Two hours. The blood still sings what the breath denies.",
    keyNumber: "2 hours",
    category: "BAC & Alcohol",
    difficulty: "Medium",
    frequency: 2
  },

  // ===== EMBER (THC / MARIJUANA) =====
  {
    id: "ember-001",
    name: "Emerald N°5",
    subtitle: "Fivefold Incantation",
    suit: "ember",
    rarity: "mythic",
    cost: 7,
    atk: 7, def: 7,
    art: "images/thc.png",
    type: "Adult THC Limit",
    rules: "Adult drivers 21+: 5.00 ng/mL of active THC in whole blood within 2 hours of driving = per se DUI under RCW 46.61.502. Even medical cannabis patients are NOT exempt.",
    flavor: "Five is the seal. Five is the key. Five is the cage.",
    keyNumber: "5.00 ng/mL",
    category: "Marijuana / THC",
    difficulty: "Easy",
    frequency: 5
  },
  {
    id: "ember-002",
    name: "Veil of Nothing",
    subtitle: "Under-21 Zero",
    suit: "ember",
    rarity: "rare",
    cost: 5,
    atk: 6, def: 6,
    art: null,
    icon: "🜍",
    type: "Zero Tolerance THC",
    rules: "Drivers under 21: ZERO TOLERANCE. ANY active THC above 0.00 ng/mL in blood within 2 hours of driving = Minor DUI. No safe trace.",
    flavor: "Nothing means nothing. Even a whisper damns you.",
    keyNumber: "0.00 ng/mL",
    category: "Marijuana / THC",
    difficulty: "Easy",
    frequency: 5
  },
  {
    id: "ember-003",
    name: "The Combined Curse",
    subtitle: "Compound Impairment",
    suit: "ember",
    rarity: "rare",
    cost: 6,
    atk: 7, def: 5,
    art: null,
    icon: "⚗️",
    type: "Combined DUI",
    rules: "Even with BOTH alcohol AND THC under their individual limits, you can be charged with DUI for being under the combined influence — if your driving is impaired.",
    flavor: "Two poisons, half each, kill twice as fast.",
    keyNumber: "Combined",
    category: "Marijuana / THC",
    difficulty: "Hard",
    frequency: 2
  },
  {
    id: "ember-004",
    name: "Sealed Reliquary",
    subtitle: "No Open Carry",
    suit: "ember",
    rarity: "common",
    cost: 2,
    atk: 2, def: 4,
    art: null,
    icon: "📦",
    type: "Possession Law",
    rules: "Marijuana in a vehicle must be in a SEALED, unopened container or in the trunk. Open containers are illegal — same as open alcohol.",
    flavor: "Locked. Sealed. Hidden. Or you are guilty.",
    keyNumber: "Sealed only",
    category: "Marijuana / THC",
    difficulty: "Medium",
    frequency: 2
  },

  // ===== STATIC (DISTRACTION / INATTENTION BLINDNESS) =====
  {
    id: "static-001",
    name: "Haunted Signal",
    subtitle: "Inattention Blindness",
    suit: "static",
    rarity: "mythic",
    cost: 6,
    atk: 8, def: 3,
    art: "images/distraction.png",
    type: "Cognitive Distraction",
    rules: "Drivers on phones — handheld OR hands-free — fail to see up to 50% of their visual environment. They look but do not perceive. This is inattention blindness.",
    flavor: "Eyes wide open. Soul nowhere near the road.",
    keyNumber: "50%",
    category: "Inattention Blindness",
    difficulty: "Easy",
    frequency: 5
  },
  {
    id: "static-002",
    name: "Hands-Free Heresy",
    subtitle: "The False Sanctuary",
    suit: "static",
    rarity: "rare",
    cost: 4,
    atk: 5, def: 5,
    art: null,
    icon: "📞",
    type: "Cognitive Load",
    rules: "Hands-free phone use is NOT safe. Cognitive load from any phone conversation increases crash risk roughly 4x — equal to handheld. The brain, not the hand, is the bottleneck.",
    flavor: "Free hands. Captured mind. Same body bag.",
    keyNumber: "4x risk",
    category: "Inattention Blindness",
    difficulty: "Medium",
    frequency: 3
  },
  {
    id: "static-003",
    name: "E-DUI Sigil",
    subtitle: "First Strike",
    suit: "static",
    rarity: "uncommon",
    cost: 3,
    atk: 3, def: 4,
    art: null,
    icon: "📱",
    type: "First Offense",
    rules: "First 'E-DUI' (driving with handheld electronics) ticket in Washington ≈ $136. Second offense within 5 years jumps to at least $234 and is reported to insurance.",
    flavor: "The phone glows. The wallet bleeds.",
    keyNumber: "$136 / $234",
    category: "Inattention Blindness",
    difficulty: "Medium",
    frequency: 3
  },
  {
    id: "static-004",
    name: "Dangerous Drift",
    subtitle: "The Secondary Sin",
    suit: "static",
    rarity: "common",
    cost: 2,
    atk: 2, def: 3,
    art: null,
    icon: "🍔",
    type: "Dangerously Distracted",
    rules: "Eating, grooming, smoking, reading — anything that causes a traffic violation is 'Dangerously Distracted' under RCW 46.61.673. Adds approximately $99 to a primary ticket.",
    flavor: "The triple-decker that cost three lives.",
    keyNumber: "$99",
    category: "Inattention Blindness",
    difficulty: "Medium",
    frequency: 2
  },

  // ===== IRON (ROAD SIGNS) =====
  {
    id: "iron-001",
    name: "STOP — Your Path Ends Here",
    subtitle: "The Crimson Octagon",
    suit: "iron",
    rarity: "forbidden",
    cost: 10,
    atk: 99, def: 99,
    art: "images/stop.png",
    type: "Regulatory · Stop",
    rules: "The OCTAGON (8-sided) is used exclusively for STOP signs. Come to a full stop at the line, check for cross traffic and pedestrians, then proceed when safe.",
    flavor: "Eight sides. Eight reasons. One law.",
    keyNumber: "Octagon = STOP",
    category: "Road Signs",
    difficulty: "Easy",
    frequency: 5
  },
  {
    id: "iron-002",
    name: "Crimson Genuflection",
    subtitle: "The Yield Triangle",
    suit: "iron",
    rarity: "rare",
    cost: 4,
    atk: 5, def: 7,
    art: "images/yield.png",
    type: "Regulatory · Yield",
    rules: "An inverted (downward-pointing) TRIANGLE means YIELD. Slow down, be ready to stop, and give the right-of-way to cross traffic or pedestrians before proceeding.",
    flavor: "Bow your head, or be broken on the asphalt.",
    keyNumber: "Triangle = YIELD",
    category: "Road Signs",
    difficulty: "Easy",
    frequency: 5
  },
  {
    id: "iron-003",
    name: "Diamond of Dread",
    subtitle: "The Yellow Warning",
    suit: "iron",
    rarity: "mythic",
    cost: 5,
    atk: 6, def: 6,
    art: "images/warning.png",
    type: "Warning",
    rules: "YELLOW DIAMOND signs are WARNINGS — hazards or changes ahead (curves, merges, slippery road, pedestrian crossings, deer). Slow down, scan, be ready.",
    flavor: "Beauty's wound: golden teeth in the night.",
    keyNumber: "Yellow ◆ = Hazard",
    category: "Road Signs",
    difficulty: "Easy",
    frequency: 5
  },
  {
    id: "iron-004",
    name: "Cinder Caution",
    subtitle: "Orange Work Zone",
    suit: "iron",
    rarity: "uncommon",
    cost: 3,
    atk: 3, def: 5,
    art: null,
    icon: "🚧",
    type: "Construction",
    rules: "ORANGE DIAMOND = work zone / construction. Slow down, watch for workers, equipment, and lane changes. Fines often DOUBLE in work zones.",
    flavor: "Orange is the color of the broken road.",
    keyNumber: "Orange ◆ = Work",
    category: "Road Signs",
    difficulty: "Easy",
    frequency: 4
  },
  {
    id: "iron-005",
    name: "The Pentagon's Watch",
    subtitle: "School Zone Sign",
    suit: "iron",
    rarity: "rare",
    cost: 4,
    atk: 4, def: 6,
    art: null,
    icon: "⬟",
    type: "School Sign",
    rules: "Fluorescent YELLOW-GREEN PENTAGON = school zone or school crossing. Watch for children. 20 mph speed limit when children are present.",
    flavor: "Five sides. Five rosary beads. Five reasons to slow.",
    keyNumber: "Pentagon = School",
    category: "Road Signs",
    difficulty: "Medium",
    frequency: 3
  },
  {
    id: "iron-006",
    name: "The Iron Circle",
    subtitle: "Railroad Crossing",
    suit: "iron",
    rarity: "uncommon",
    cost: 3,
    atk: 4, def: 4,
    art: null,
    icon: "🚂",
    type: "Railroad Warning",
    rules: "Yellow CIRCLE with black X and 'RR' = railroad crossing advance warning. Slow, look, listen, be prepared to stop. Trains can come from either direction.",
    flavor: "The circle does not lie. Listen for the iron song.",
    keyNumber: "Circle = RR",
    category: "Road Signs",
    difficulty: "Medium",
    frequency: 3
  },
  {
    id: "iron-007",
    name: "The Forbidden Pennant",
    subtitle: "No Passing Zone",
    suit: "iron",
    rarity: "rare",
    cost: 5,
    atk: 5, def: 5,
    art: null,
    icon: "▷",
    type: "No Passing",
    rules: "A horizontal PENNANT (yellow, pointed sideways) on the LEFT side of the road marks the START of a NO PASSING ZONE. Do not pass other vehicles in this stretch.",
    flavor: "The arrow points; the road forbids.",
    keyNumber: "Pennant = No Pass",
    category: "Road Signs",
    difficulty: "Hard",
    frequency: 2
  },
  {
    id: "iron-008",
    name: "Color Catechism",
    subtitle: "Red of Prohibition",
    suit: "iron",
    rarity: "common",
    cost: 2,
    atk: 2, def: 3,
    art: null,
    icon: "🟥",
    type: "Color Code",
    rules: "RED on a sign = STOP, YIELD, PROHIBITION, or WRONG WAY. Red signals an immediate action required or that something is forbidden.",
    flavor: "Red is the only word the road must scream.",
    keyNumber: "Red = Stop/No",
    category: "Road Signs",
    difficulty: "Easy",
    frequency: 4
  },
  {
    id: "iron-009",
    name: "Verdant Wayfinder",
    subtitle: "Green Guide",
    suit: "iron",
    rarity: "common",
    cost: 1,
    atk: 1, def: 2,
    art: null,
    icon: "🟩",
    type: "Color Code",
    rules: "GREEN signs are GUIDES — destinations, distances, exits, and street names. Movement is permitted.",
    flavor: "Follow the green and you find your name on the map.",
    keyNumber: "Green = Guide",
    category: "Road Signs",
    difficulty: "Easy",
    frequency: 3
  },
  {
    id: "iron-010",
    name: "Azure Refuge",
    subtitle: "Blue Services",
    suit: "iron",
    rarity: "common",
    cost: 1,
    atk: 1, def: 2,
    art: null,
    icon: "🟦",
    type: "Color Code",
    rules: "BLUE signs indicate MOTORIST SERVICES (gas, food, lodging, hospitals, rest areas, accessible parking).",
    flavor: "Blue is the color of mercy on a long road.",
    keyNumber: "Blue = Services",
    category: "Road Signs",
    difficulty: "Easy",
    frequency: 2
  },

  // ===== THORN (RIGHT OF WAY) =====
  {
    id: "thorn-001",
    name: "Crossroads of Dawn",
    subtitle: "Uncontrolled Intersection",
    suit: "thorn",
    rarity: "mythic",
    cost: 6,
    atk: 7, def: 7,
    art: "images/intersection.png",
    type: "Right of Way",
    rules: "At an uncontrolled intersection, two vehicles arriving at the same time: the vehicle on the RIGHT has right-of-way. The driver on the left must yield.",
    flavor: "When two paths meet, the right hand wins the duel.",
    keyNumber: "Right wins",
    category: "Right-of-Way",
    difficulty: "Easy",
    frequency: 5
  },
  {
    id: "thorn-002",
    name: "Roundabout Witch",
    subtitle: "Eternal Loop",
    suit: "thorn",
    rarity: "mythic",
    cost: 7,
    atk: 7, def: 8,
    art: "images/roundabout.png",
    type: "Roundabout",
    rules: "At a roundabout: YIELD to drivers ALREADY IN the circle. Enter only when there is a safe gap. Travel counter-clockwise. Yield to pedestrians at every crossing.",
    flavor: "The wheel turns one way only. Step in time or be devoured.",
    keyNumber: "Yield to circle",
    category: "Right-of-Way",
    difficulty: "Medium",
    frequency: 3
  },
  {
    id: "thorn-003",
    name: "The Crimson Procession",
    subtitle: "Emergency Vehicle",
    suit: "thorn",
    rarity: "mythic",
    cost: 5,
    atk: 6, def: 6,
    art: "images/emergency.png",
    type: "Yielding",
    rules: "Emergency vehicle with lights AND sirens approaching: pull to the RIGHT edge of the road and STOP until it passes. If in an intersection, clear it first, then pull right.",
    flavor: "Pull right. Bow. Let the wings of death pass over.",
    keyNumber: "Right + Stop",
    category: "Right-of-Way",
    difficulty: "Easy",
    frequency: 4
  },
  {
    id: "thorn-004",
    name: "Phantom School Bus",
    subtitle: "Spectral Stop",
    suit: "thorn",
    rarity: "forbidden",
    cost: 9,
    atk: 9, def: 9,
    art: "images/bus.png",
    type: "School Bus",
    rules: "School bus with flashing RED lights on a 2-LANE road: ALL traffic stops from BOTH directions. On a DIVIDED highway (physical median): only the bus's direction must stop.",
    flavor: "Children pass like ghosts. The bus is judgment in yellow.",
    keyNumber: "Both dirs / divided=one",
    category: "Right-of-Way",
    difficulty: "Hard",
    frequency: 4
  },
  {
    id: "thorn-005",
    name: "Garden of Crosswalks",
    subtitle: "Pedestrian Right",
    suit: "thorn",
    rarity: "rare",
    cost: 4,
    atk: 4, def: 7,
    art: "images/pedestrian.png",
    type: "Pedestrian",
    rules: "Always yield to pedestrians at marked AND unmarked crosswalks. If a pedestrian is in or entering the crosswalk on your half of the road, STOP until they fully clear your side.",
    flavor: "Soft feet, hard law. They walk; you wait.",
    keyNumber: "Always yield",
    category: "Right-of-Way",
    difficulty: "Easy",
    frequency: 5
  },
  {
    id: "thorn-006",
    name: "Sinister Turn",
    subtitle: "Left Yield",
    suit: "thorn",
    rarity: "rare",
    cost: 4,
    atk: 5, def: 5,
    art: null,
    icon: "↰",
    type: "Left Turn",
    rules: "Turning LEFT at an intersection: yield to ALL oncoming traffic in the intersection or close enough to be an immediate hazard, AND to pedestrians crossing your path (RCW 46.61.185).",
    flavor: "The left hand pays. The left hand waits.",
    keyNumber: "Yield all oncoming",
    category: "Right-of-Way",
    difficulty: "Easy",
    frequency: 5
  },
  {
    id: "thorn-007",
    name: "Order of Arrival",
    subtitle: "Four-Way Stop",
    suit: "thorn",
    rarity: "uncommon",
    cost: 3,
    atk: 3, def: 5,
    art: null,
    icon: "✚",
    type: "4-Way Stop",
    rules: "At a 4-way STOP: the vehicle that ARRIVED FIRST goes first. If two arrive at the same time, the one on the RIGHT goes. Pedestrians always go before vehicles.",
    flavor: "First in, first out. Tie? The right always wins.",
    keyNumber: "First / Right",
    category: "Right-of-Way",
    difficulty: "Easy",
    frequency: 4
  },
  {
    id: "thorn-008",
    name: "The Severed T",
    subtitle: "T-Junction Yield",
    suit: "thorn",
    rarity: "uncommon",
    cost: 3,
    atk: 3, def: 4,
    art: null,
    icon: "⊤",
    type: "T-Intersection",
    rules: "At a T-intersection with no signs or signals: the driver on the road that ENDS (the stem of the T) must yield to traffic on the through road.",
    flavor: "When the path ends, kneel before the road that does not.",
    keyNumber: "Stem yields",
    category: "Right-of-Way",
    difficulty: "Medium",
    frequency: 2
  },

  // ===== BONE (SPEED & NUMBERS) =====
  {
    id: "bone-001",
    name: "Hell Kitty: Night Racer",
    subtitle: "Highway Speed",
    suit: "bone",
    rarity: "mythic",
    cost: 6,
    atk: 9, def: 4,
    art: "images/speed.png",
    type: "State Highway",
    rules: "Unposted speed limit on a WASHINGTON STATE HIGHWAY is 60 mph. (County roads: 50 mph.) Always slower if posted or if conditions demand.",
    flavor: "Sixty: the heartbeat of the asphalt witch.",
    keyNumber: "60 mph",
    category: "Speed & Numbers",
    difficulty: "Medium",
    frequency: 2
  },
  {
    id: "bone-002",
    name: "Lantern of Twenty",
    subtitle: "School Zone Speed",
    suit: "bone",
    rarity: "rare",
    cost: 4,
    atk: 4, def: 6,
    art: "images/school.png",
    type: "School Zone Speed",
    rules: "20 mph in posted school zones when children are present. The slowest speed Washington requires. Cameras enforce it.",
    flavor: "Twenty, for the small souls. Twenty, or you are damned.",
    keyNumber: "20 mph",
    category: "Speed & Numbers",
    difficulty: "Easy",
    frequency: 4
  },
  {
    id: "bone-003",
    name: "City of Twenty-Five",
    subtitle: "Town Streets",
    suit: "bone",
    rarity: "common",
    cost: 2,
    atk: 2, def: 4,
    art: null,
    icon: "🏙️",
    type: "City Speed",
    rules: "Unposted speed limit on streets within Washington cities and towns is 25 mph.",
    flavor: "Stone walls, stone hearts, stone speed.",
    keyNumber: "25 mph",
    category: "Speed & Numbers",
    difficulty: "Easy",
    frequency: 3
  },
  {
    id: "bone-004",
    name: "County Crow",
    subtitle: "County Road Speed",
    suit: "bone",
    rarity: "uncommon",
    cost: 3,
    atk: 3, def: 4,
    art: null,
    icon: "🐦‍⬛",
    type: "County Speed",
    rules: "Unposted speed limit on Washington county roads is 50 mph.",
    flavor: "The crow knows the back roads run at fifty.",
    keyNumber: "50 mph",
    category: "Speed & Numbers",
    difficulty: "Medium",
    frequency: 2
  },
  {
    id: "bone-005",
    name: "Hundred-Foot Herald",
    subtitle: "Signal Distance",
    suit: "bone",
    rarity: "common",
    cost: 2,
    atk: 2, def: 3,
    art: null,
    icon: "↗",
    type: "Signaling",
    rules: "Signal at least 100 FEET in advance before a turn or lane change. Cancel the signal after completing the maneuver.",
    flavor: "Announce yourself before the asphalt swallows you.",
    keyNumber: "100 ft",
    category: "Speed & Numbers",
    difficulty: "Medium",
    frequency: 2
  },
  {
    id: "bone-006",
    name: "Twin Lanterns",
    subtitle: "High Beam Etiquette",
    suit: "bone",
    rarity: "uncommon",
    cost: 3,
    atk: 3, def: 3,
    art: null,
    icon: "💡",
    type: "Night Driving",
    rules: "Dim high beams within 500 FEET of an oncoming vehicle and within 300 FEET when following another vehicle.",
    flavor: "Bright eyes blind the night. Bow your light to others.",
    keyNumber: "500 / 300 ft",
    category: "Speed & Numbers",
    difficulty: "Medium",
    frequency: 2
  },
  {
    id: "bone-007",
    name: "Three-Foot Vow",
    subtitle: "Bicycle Clearance",
    suit: "bone",
    rarity: "rare",
    cost: 3,
    atk: 4, def: 4,
    art: null,
    icon: "🚲",
    type: "Sharing the Road",
    rules: "When passing a bicyclist in Washington, leave at least 3 FEET of clearance.",
    flavor: "Three feet of mercy. The vow of the kind driver.",
    keyNumber: "3 ft",
    category: "Speed & Numbers",
    difficulty: "Easy",
    frequency: 3
  },
  {
    id: "bone-008",
    name: "Four-Second Shroud",
    subtitle: "Following Distance",
    suit: "bone",
    rarity: "common",
    cost: 2,
    atk: 1, def: 5,
    art: null,
    icon: "⏱",
    type: "Following Rule",
    rules: "Maintain at least 4 SECONDS of following distance behind the vehicle ahead in normal conditions. Add more in rain, fog, ice, night, or heavy load.",
    flavor: "Four seconds is the breath between life and the crunch.",
    keyNumber: "4 sec",
    category: "Speed & Numbers",
    difficulty: "Easy",
    frequency: 2
  },
  {
    id: "bone-009",
    name: "Curb's Embrace",
    subtitle: "Parallel Park",
    suit: "bone",
    rarity: "common",
    cost: 1,
    atk: 1, def: 3,
    art: null,
    icon: "🅿️",
    type: "Parking",
    rules: "Your vehicle must be parked within 12 INCHES of the curb when parallel parking.",
    flavor: "One foot from the stone. One foot from the fine.",
    keyNumber: "12 in",
    category: "Speed & Numbers",
    difficulty: "Hard",
    frequency: 1
  },
  {
    id: "bone-010",
    name: "Four-Day Reckoning",
    subtitle: "Crash Report",
    suit: "bone",
    rarity: "uncommon",
    cost: 3,
    atk: 2, def: 5,
    art: null,
    icon: "📝",
    type: "Reporting",
    rules: "You must report crashes involving injury, death, or more than $1,000 in property damage WITHIN 4 DAYS.",
    flavor: "The page does not forgive a fifth day.",
    keyNumber: "4 days",
    category: "Speed & Numbers",
    difficulty: "Hard",
    frequency: 2
  }
];

// ============================================================
// DUEL MODE — Practice test questions
// ============================================================
const QUIZ = [
  { q: "What is the legal BAC limit for a 25-year-old driver in Washington?",
    options: ["0.02%", "0.04%", "0.08%", "0.10%"], answer: 2, topic: "BAC & Alcohol", cardId: "blood-001",
    explain: "0.08% is the per se DUI threshold for adults 21+ under RCW 46.61.502." },
  { q: "A 19-year-old is stopped with a BAC of 0.03%. What is the result in Washington?",
    options: ["No charge — under the adult limit", "Minor DUI misdemeanor (RCW 46.61.503)", "Felony DUI", "Reckless driving only"],
    answer: 1, topic: "BAC & Alcohol", cardId: "blood-002",
    explain: "Zero-tolerance: any BAC of 0.02%+ for under-21 = Minor DUI." },
  { q: "What is the BAC limit while operating a commercial vehicle in Washington?",
    options: ["0.02%", "0.04%", "0.06%", "0.08%"], answer: 1, topic: "BAC & Alcohol", cardId: "blood-003",
    explain: "Commercial drivers face a 0.04% BAC limit — half the standard adult limit." },
  { q: "What BAC level triggers AGGRAVATED DUI penalties in Washington?",
    options: ["0.10%", "0.12%", "0.15%", "0.20%"], answer: 2, topic: "BAC & Alcohol", cardId: "blood-004",
    explain: "0.15% or higher = enhanced penalties: longer suspension, mandatory interlock, more jail." },
  { q: "If you refuse a chemical (breath/blood) test in Washington, your license can be suspended for:",
    options: ["30 days", "60 days", "90–730 days", "Only the day of arrest"],
    answer: 2, topic: "BAC & Alcohol", cardId: "blood-005",
    explain: "Implied-consent refusal: 90–730 days (or until 21, whichever is longer)." },
  { q: "Within how many hours of driving must a BAC/THC sample be taken for per se DUI?",
    options: ["1 hour", "2 hours", "3 hours", "6 hours"],
    answer: 1, topic: "BAC & Alcohol", cardId: "blood-006",
    explain: "WA law uses a 2-hour measurement window after driving." },
  { q: "What is the legal active THC limit (ng/mL) for adult drivers in Washington?",
    options: ["1.00", "2.00", "5.00", "10.00"], answer: 2, topic: "Marijuana / THC", cardId: "ember-001",
    explain: "5.00 ng/mL in whole blood within 2 hours = per se DUI under RCW 46.61.502." },
  { q: "An 18-year-old driver tests at 1 ng/mL THC. Can they be charged?",
    options: ["No — below 5 ng/mL", "Yes — any THC over 0.00 is illegal under 21", "Only if visibly impaired", "Only with a prior offense"],
    answer: 1, topic: "Marijuana / THC", cardId: "ember-002",
    explain: "Under 21 = zero tolerance; any detectable THC can be a Minor DUI." },
  { q: "Can you be charged with DUI when alcohol AND THC are BOTH below their per se limits?",
    options: ["No — under limits = safe", "Yes — combined influence can still impair (RCW 46.61.502)", "Only if BAC is over 0.05", "Only on freeways"],
    answer: 1, topic: "Marijuana / THC", cardId: "ember-003",
    explain: "You can be charged for combined influence even if each is below its individual limit." },
  { q: "How must marijuana be carried in a vehicle in Washington?",
    options: ["Any container is fine", "Sealed, unopened container or in the trunk", "Only in the glovebox", "Locked in a metal box"],
    answer: 1, topic: "Marijuana / THC", cardId: "ember-004",
    explain: "Sealed, unopened, or in the trunk. Open containers are illegal." },
  { q: "How much of their visual environment can drivers on cell phones miss?",
    options: ["10%", "25%", "Up to 50%", "Up to 90%"],
    answer: 2, topic: "Inattention Blindness", cardId: "static-001",
    explain: "National Safety Council research cited in WA Driver Guide: up to 50% missed = inattention blindness." },
  { q: "Is hands-free phone use safe while driving?",
    options: ["Yes — hands on the wheel", "Yes, if under 5 minutes", "No — cognitive load still causes inattention blindness", "Only legal on highways"],
    answer: 2, topic: "Inattention Blindness", cardId: "static-002",
    explain: "Both handheld and hands-free conversations roughly quadruple crash risk." },
  { q: "What is the approximate fine for a FIRST E-DUI (handheld electronics) ticket in Washington?",
    options: ["$50", "$99", "$136", "$500"],
    answer: 2, topic: "Inattention Blindness", cardId: "static-003",
    explain: "First E-DUI ≈ $136. Second within 5 years ≈ $234+ and reported to insurance." },
  { q: "Eating a cheeseburger and committing a traffic violation as a result is what offense in Washington?",
    options: ["Reckless driving", "E-DUI", "Dangerously Distracted (RCW 46.61.673)", "Negligent driving"],
    answer: 2, topic: "Inattention Blindness", cardId: "static-004",
    explain: "It's a secondary offense — adds ~$99 to a primary ticket." },
  { q: "An OCTAGON-shaped sign always means:",
    options: ["Yield", "Stop", "Warning", "Do Not Enter"],
    answer: 1, topic: "Road Signs", cardId: "iron-001",
    explain: "The 8-sided octagon is used exclusively for STOP." },
  { q: "What does an inverted (downward) TRIANGLE sign mean?",
    options: ["No U-turn", "Yield", "Warning", "Construction"],
    answer: 1, topic: "Road Signs", cardId: "iron-002",
    explain: "An inverted red-and-white triangle is exclusively a YIELD sign." },
  { q: "A YELLOW DIAMOND sign means:",
    options: ["Stop", "Yield", "Warning of hazard ahead", "School zone only"],
    answer: 2, topic: "Road Signs", cardId: "iron-003",
    explain: "Yellow diamond = warning. Slow down and scan." },
  { q: "An ORANGE diamond sign means:",
    options: ["School zone", "Work zone / construction ahead", "Sharp curves", "Recreation area"],
    answer: 1, topic: "Road Signs", cardId: "iron-004",
    explain: "Orange is reserved for construction and maintenance zones." },
  { q: "A fluorescent yellow-green PENTAGON sign means:",
    options: ["Hospital", "Railroad crossing", "School zone / school crossing", "Park"],
    answer: 2, topic: "Road Signs", cardId: "iron-005",
    explain: "Fluorescent yellow-green pentagons are used only for school signs." },
  { q: "A CIRCULAR yellow sign with a large X and 'RR' is:",
    options: ["No U-turn", "Railroad crossing advance warning", "Roundabout ahead", "Radio tower"],
    answer: 1, topic: "Road Signs", cardId: "iron-006",
    explain: "Yellow circle = RR crossing advance warning. Slow, look, listen." },
  { q: "A horizontal yellow PENNANT on the LEFT side of the road marks:",
    options: ["End of speed zone", "No passing zone", "Lane shift", "Detour"],
    answer: 1, topic: "Road Signs", cardId: "iron-007",
    explain: "The pennant points the way and bars passing in this stretch." },
  { q: "On highway signs, BLUE indicates:",
    options: ["Construction", "Warnings", "Motorist services and accessible parking", "Routes"],
    answer: 2, topic: "Road Signs", cardId: "iron-010",
    explain: "Blue = motorist services. Green = directions/destinations." },
  { q: "Two vehicles arrive at an uncontrolled intersection at the same time. Who has the right-of-way?",
    options: ["Larger vehicle", "Vehicle on the left", "Vehicle on the RIGHT", "Whoever signals first"],
    answer: 2, topic: "Right-of-Way", cardId: "thorn-001",
    explain: "Vehicle on the right wins. Driver on the left must yield." },
  { q: "When approaching a roundabout, you must:",
    options: ["Stop and wait for all cars to clear", "Yield to drivers already IN the roundabout", "Take the right-of-way", "Honk before entering"],
    answer: 1, topic: "Right-of-Way", cardId: "thorn-002",
    explain: "Circulating traffic has right-of-way; you yield as you enter." },
  { q: "An emergency vehicle with lights and sirens is approaching. You should:",
    options: ["Speed up", "Pull LEFT and stop", "Pull RIGHT and stop", "Maintain speed"],
    answer: 2, topic: "Right-of-Way", cardId: "thorn-003",
    explain: "Pull right and stop until it has passed." },
  { q: "A school bus with FLASHING RED lights is stopped on a 2-lane road. You must:",
    options: ["Slow to 20 mph and continue", "Stop only if going the same direction", "Stop from BOTH directions", "Pass quickly on the left"],
    answer: 2, topic: "Right-of-Way", cardId: "thorn-004",
    explain: "Both directions stop on undivided roads. Only same-direction stops on divided highways." },
  { q: "When must you yield to a pedestrian at a crosswalk in Washington?",
    options: ["Only at marked crosswalks", "Only at school zones", "At marked AND unmarked crosswalks", "Only when they wave"],
    answer: 2, topic: "Right-of-Way", cardId: "thorn-005",
    explain: "Always yield at marked AND unmarked crosswalks; stop until they clear your side." },
  { q: "Turning LEFT at a green light with no arrow — you must yield to:",
    options: ["Only pedestrians", "Only oncoming cars", "Oncoming traffic AND pedestrians crossing", "Nobody — green means go"],
    answer: 2, topic: "Right-of-Way", cardId: "thorn-006",
    explain: "RCW 46.61.185 — left-turners yield to oncoming traffic and pedestrians." },
  { q: "The unposted speed limit on a Washington STATE HIGHWAY is:",
    options: ["50 mph", "55 mph", "60 mph", "70 mph"],
    answer: 2, topic: "Speed & Numbers", cardId: "bone-001",
    explain: "60 mph on state highways. 50 mph on county roads. 25 mph in cities. 20 mph in school zones." },
  { q: "The unposted speed limit in a Washington school zone is:",
    options: ["15 mph", "20 mph", "25 mph", "30 mph"],
    answer: 1, topic: "Speed & Numbers", cardId: "bone-002",
    explain: "20 mph when children are present." },
  { q: "The unposted speed limit on a Washington city or town street is:",
    options: ["20 mph", "25 mph", "30 mph", "35 mph"],
    answer: 1, topic: "Speed & Numbers", cardId: "bone-003",
    explain: "25 mph on city/town streets unless otherwise posted." },
  { q: "How far in advance must you signal a turn or lane change?",
    options: ["25 feet", "50 feet", "100 feet", "300 feet"],
    answer: 2, topic: "Speed & Numbers", cardId: "bone-005",
    explain: "100 feet before the turn or lane change. Cancel after." },
  { q: "How much space must you give when passing a bicyclist in Washington?",
    options: ["1 foot", "2 feet", "3 feet", "6 feet"],
    answer: 2, topic: "Speed & Numbers", cardId: "bone-007",
    explain: "Washington law requires at least 3 feet clearance." },
  { q: "Within how many days must you report a crash with injury, death, or over $1,000 damage?",
    options: ["1 day", "2 days", "4 days", "10 days"],
    answer: 2, topic: "Speed & Numbers", cardId: "bone-010",
    explain: "4 days to report a qualifying crash." }
];

// Essential numbers — the boss cheat sheet
const NUMBERS = [
  { num: "0.08%", label: "Adult BAC limit (21+)", suit: "blood" },
  { num: "0.04%", label: "Commercial driver BAC limit", suit: "blood" },
  { num: "0.02%", label: "Under-21 BAC limit (zero tolerance)", suit: "blood" },
  { num: "0.15%", label: "Aggravated DUI threshold", suit: "blood" },
  { num: "5.00 ng/mL", label: "Adult THC per se DUI limit", suit: "ember" },
  { num: "0.00 ng/mL", label: "Under-21 THC limit (zero tolerance)", suit: "ember" },
  { num: "2 hours", label: "Window for BAC/THC measurement", suit: "blood" },
  { num: "50%", label: "Visual info missed during phone use", suit: "static" },
  { num: "$136", label: "First E-DUI ticket (handheld phone)", suit: "static" },
  { num: "$234+", label: "Second E-DUI ticket within 5 years", suit: "static" },
  { num: "$99", label: "Dangerously Distracted (secondary)", suit: "static" },
  { num: "20 mph", label: "School zone speed limit", suit: "bone" },
  { num: "25 mph", label: "City/town street speed limit", suit: "bone" },
  { num: "50 mph", label: "County road speed limit", suit: "bone" },
  { num: "60 mph", label: "State highway speed limit", suit: "bone" },
  { num: "100 ft", label: "Signal distance before turn/lane change", suit: "bone" },
  { num: "500 ft", label: "Dim high beams (oncoming)", suit: "bone" },
  { num: "300 ft", label: "Dim high beams (following)", suit: "bone" },
  { num: "3 ft", label: "Clearance when passing a bicycle", suit: "bone" },
  { num: "12 in", label: "Max distance from curb (parallel park)", suit: "bone" },
  { num: "4 sec", label: "Following distance rule", suit: "bone" },
  { num: "4 days", label: "Crash report deadline (injury / >$1k)", suit: "bone" },
  { num: "90–730 days", label: "Suspension for chemical-test refusal", suit: "blood" }
];
